### ISSUE TITLE
Tables not updating correctly - refreshing the page resolves it

### ISSUE THREAD

**Issue by victorhooi** [Zodiase/meteor-mdl#10]
I'm using the CSS from material-design-lite, along with the MDL JS from your package.

I have a MDL table - when I add/remove data to it reactively, the columns seem to be off by one:

![screenshot 2015-08-12 22 37 13](https://cloud.githubusercontent.com/assets/243499/9224102/4449d0f4-4143-11e5-8764-0781bcec74dc.png)

If I refresh the page, the table then renders correctly:

![screenshot 2015-08-12 22 47 18](https://cloud.githubusercontent.com/assets/243499/9224212/1cedb68c-4144-11e5-8d42-43e9b961b61d.png)

Is this something funny with the way MDL/Blaze are updating the page?

How do you go about updating the MDL JavaScript file to the latest?

**Comment by Zodiase** [comment]
@victorhooi Hey thanks for pointing this out!
I think the `mdl-data-table--selectable` option for data tables is really broken. According to [this line](https://github.com/google/material-design-lite/blob/master/src/data-table/data-table.js#L137), MDL only adds those checkboxes at the time of upgrading a data table. **If any row is added after the upgrading, no checkbox will be added**. In short, I think **this is a usability bug in MDL**. Specifically this issue google/material-design-lite#984 talks about this. From the logic of the cause, the workaround is to somehow **force re-render the whole data table** so MDL could do another upgrading on it. Unfortunately at the moment I don't have an idea how Meteor could do that or how this package could provide the workaround. Also this workaround is _very very bad_ performance-wise so personally I'd rather implement those checkboxes without using the `mdl-data-table--selectable` option so this issue could be avoided.

About how I keep MDL updated, I monitor my fork of google/material-design-lite daily and if I see a bump of the version, I pull the changes and rebuild the `material.js` in this package.

**Comment by Zodiase** [comment]
There are [quite many issues related to the data table component](https://github.com/google/material-design-lite/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+data+table+).

**Comment by Zodiase** [comment]
I would strongly recommend avoid using `mdl-data-table--selectable` and if you need the checkboxes, implement them on your own.

**Comment by Zodiase** [comment]
Check out the demo project to see how the checkboxes could be easily implemented without using `mdl-data-table--selectable`.
