### ISSUE TITLE
example: of Material Icons Typeface

### ISSUE THREAD

**Issue by 6gsaifulislam** [Zodiase/meteor-mdl#17]
v1.0.2-1 Included Material Icons Typeface file in the package so your app can go completely offline.

Could you please provide example of how to use MDL lite Icons using the offline version.

**Comment by Zodiase** [comment]
https://www.google.com/design/icons/ has the complete list of all available icons. Find what interests you, note its name, "3d rotation" for example, use underlines in the place of spaces and use this html code:

``` HTML
<i class="material-icons">3d_rotation</i>
```

Note that the tag could be anything as long as it supports inner text nodes. With the class `material-icons`, the text inside would be rendered as the corresponding icon. And you could also style its color and size.

**Comment by 6gsaifulislam** [comment]
Thanks that is the same format I have been using, did a meteor update and the icons display ok even when disconnected from network.  I normally run a meteor update once a week - must have missed the updated versions.

**Comment by Zodiase** [comment]
That might be the issue with meteor package manager. I follow the package versioning instruction and use mainVersion-revision format but somehow meteor package manager considers 1.0.1 more up-to-date than 1.0.1-1 for example. I tested and found even with 1.0.2-1 released, using meteor update always gets me 1.0.2 instead. I had to do `meteor add zodiac:mdl@=1.0.2-1` to work around.
