### ISSUE TITLE
Form submit event doesn't fire

### ISSUE THREAD

**Issue by vnmone** [Zodiase/meteor-mdl#25]
Here is meteorPad example:
http://meteorpad.com/pad/zjtAP3zeFQBAth2ax/Copy%20of%20material-design-lite-test

submit event doesn't fire.

without mdl pack works properly

**Comment by Zodiase** [comment]
Duplicate of #2.

**Comment by Zodiase** [comment]
In short, blaze (Template) events are registered on the root element(s) of individual templates. However, MDL components sometimes shift elements around. In this case, for example, the layout component would create a wrapper container element and move itself inside that container. During this process, all the event listeners associated with the root element (the mdl-layout element) get destroyed.

**Comment by vnmone** [comment]
Sorry for my blindness.
