### ISSUE TITLE
Fix README in section  'more than pre-built themes'

### ISSUE THREAD

**Issue by MBThaumatec** [Zodiase/meteor-mdl#27]
Hey, another very small issue this time.
In readme there is this code:

```
// mdl-theme.scss
$color-primary: #FFF;
$color-accent: #000;
@import '{zodiase:mdl}/theme';
```

which is not working at all. In color description MDL describes colors like this: 

```
$palette-pink:
"252,228,236"
...
$palette-pink-50: nth($palette-pink, 1);
```

So this part of readme should be actually like this:

```
$color-primary: "0,0,0";
$color-accent: "252,228,236";
@import '{zodiase:mdl}/theme';
```

Giving color in rgb with # or function don't work. This is only way for me to start custom theme working.

**Comment by Zodiase** [comment]
You are right! I completely didn't think about it when writing the readme... The SASS code is actually placing the variables inside "rgba()" so yes you have to use "r,g,b".
