### ISSUE TITLE
Cannot call method 'addJavaScript' of null

### ISSUE THREAD

**Issue by cirocolares** [Zodiase/meteor-mdl#29]
hi!

I installed the package, created the zodiase-mdl.json file and when I try to run the app, I'm facing the error below... Someone knows why I'm getting this error?

thanks!

=> Started proxy.  
=> Started MongoDB.                           
- zodiase:mdl > Enabled with default settings. See documentation for customization options.
- zodiase:mdl > Using settings: { jsLib: { minified: false },
  theme: { primary: 'indigo', accent: 'pink' },
  patches: { autoUpgrade: 'fullUpgrade', applyListIconFix: true },
  verbose: false }
- zodiase:mdl > Using settings: { jsLib: { minified: false },
  theme: { primary: 'indigo', accent: 'pink' },
  patches: { autoUpgrade: 'fullUpgrade', applyListIconFix: true },
  verbose: false }
  => Errors prevented startup:                  
  
  While processing files with zodiase:mdl (for target web.cordova):
  plugin/build.js:175:18: Cannot call method 'addJavaScript' of null (at
  Compiler.processFilesForTarget)

=> Your application has errors. Waiting for file change.

**Comment by Zodiase** [comment]
I'm sorry to see this happen. Unfortunately the current test cases do not cover platforms other than `web.browser` so this error was not spotted before publishing. I'll have a fix out very soon. Could you then clone the package from repo and test it as a local package?

**Comment by Zodiase** [comment]
The fix is out. If you could test it out as a local package, I could see if further adjustments are needed. Thanks.

**Comment by Zodiase** [comment]
This issue actually affects all versions since `1.0.6_4` for platforms other than `web.browser`. So before the fix is published, you could stay at version `1.0.6_3` to avoid this error.

**Comment by cirocolares** [comment]
Hi! Sorry for the delay. The issue was fixed, the package is working fine now!
Thank you very much!
