### ISSUE TITLE
MDl disabled. Create a file named 'zodiase-mdl.json' at the root of the app to enable. (Meteor 1.3.2.2)

### ISSUE THREAD

**Issue by Antoine-O** [Zodiase/meteor-mdl#37]
Hello !
Of Course I have created the file but he keeps asking,
Tried a meteor reset without success.
any idea ?
tried to put things in zodiase-mdl.json

```
{
  "theme": {
    "primary": "deep_orange",
    "accent": "blue"
  }
}
```

no effects.

**Comment by Zodiase** [comment]
Here's a repo of a minimal Meteor app (1.3.2.2) with `zodiase:mdl` (1.1.3_1) that's running without any errors: https://github.com/Zodiase/test__meteor-1.3.2.2__mdl-1.1.3_1.

While I don't know what caused the issue you are experiencing, I hope that minimal app could help you find the cause. Or if you could give a minimal demo reproducing the error, that'd help me find the cause.

**Comment by Antoine-O** [comment]
My bad it was due to a missing (mistyped) template.
thx and keep up the good work :)
