### ISSUE TITLE
Meteor.logout Not working

### ISSUE THREAD

**Issue by kokjinsam** [Zodiase/meteor-mdl#4]
Hey,

Thanks for making this package! It's really neat and nice!

```
<a class="mdl-navigation__link" href="" id="logout">Sign Out</a>

Template.layerOneMain.events({
'click #logout': function (event, tmpl) {
    console.log('h');
    Meteor.logout(function() {
        console.log('Sign out success');
        Router.go('home');
    });

    return false;
}
});
```

I tried to do Meteor.logout() but it didn't work. Then I removed your package from my app and the logout function worked properly. The click event was not registered. Can you please take a look? Thanks!

**Comment by Zodiase** [comment]
@skaxwng
I'm glad you like it :)

Is the `<a class="mdl-navigation__link" href="" id="logout">Sign Out</a>` inside another MDL component? If so, it's known in issue #2 that, well, this happens. I'll look into that.

I'd like to make sure this is not another bug. So I guess you don't even get the result of `console.log('h');` in console, right? And would it work if you call `Meteor.logout()` in the console? If so then this is exactly what issue #2 is about.

**Comment by kokjinsam** [comment]
Yes, the link is within another MDL component and no result from console.log('h'). Meteor.logout() works in the console. 

Thanks for fixing the bug! Look forward to it.

**Comment by Zodiase** [comment]
I found the cause and the solution, see issue #2.
