### ISSUE TITLE
Reactive available?

### ISSUE THREAD

**Issue by lesliechw** [Zodiase/meteor-mdl#42]
Hi,

Is reactive function still exist when using meteor-mdl? Please advice, thank you.

**Comment by Zodiase** [comment]
I'm not sure I understand your question. What do you want to achieve?

**Comment by lesliechw** [comment]
I mean will it work as Blaze on UI auto update.

**Comment by Zodiase** [comment]
If you mean "If I use Blaze to dynamically render a MDL Component, will the component get upgraded (a MDL thing)?" then the answer is "most likely yes, unless you rendered it wrong". 

If you mean "If I put a MDL Component in a Blaze template and the component has reactive data in it, will everything work perfectly?" then the answer is "likely no". Reactive content in Blaze can break a lot of third-party libraries/frameworks that maintain their own internal states. You have to know enough to avoid such mistakes, unfortunately.

I'm using this package in almost all of my Meteor apps and it works just fine with Blaze. Although there are quite a few quirks and issues to know about, don't feel discouraged. If you encounter any specific issues or difficulties, let me know and I'll try to help you out.

**Comment by ramijarrar** [comment]
Probably worth taking a look at #30, once you get your head that it should be fairly straight-forward to figure out the best way to pair MDL/Blaze components (for most cases). I would watch v2 of MDL as well which is going to resolve a lot of the issues with templating libraries.

**Comment by lesliechw** [comment]
Thank you very much for your support. I'm very new to JavaScript/EcmaScript
and self learning. I'll take your advice and try it myself.

**Comment by Zodiase** [comment]
I take the last response as this issue may be closed. If you need more help please comment below.
