### ISSUE TITLE
Build includes every verison 

### ISSUE THREAD

**Issue by ForsakenHarmony** [Zodiase/meteor-mdl#44]
As the title says every color combination is included in the tar file produced

This got my file from 7 to 38 MB

**Comment by Zodiase** [comment]
And that is an issue because you can't afford 31MB of extra storage?

**Comment by ForsakenHarmony** [comment]
It's an issue because it's unnecessary

**Comment by Zodiase** [comment]
Well, unfortunately the goal of this package is not achieving best efficiency. Not only does it not try to use as little storage as possible, the auto-upgrade helper involving MutationObserver isn't the most efficient solution either. With this package, I hope anyone would be able to have an easy start with MDL in Meteor with different levels of customization (theme changing and SASS support). All of these come at a cost. For maximum efficiency you would want to have a custom build for your needs and pick the best timing for upgrading MDL components.

For the next major version, if such a package is still needed after the release of MDL v2, I'll separate themes, SASS and JS logic into different packages, so unnecessary stuff can be opted out.
