### ISSUE TITLE
Dynamic Tabs

### ISSUE THREAD

**Issue by Antoine-O** [Zodiase/meteor-mdl#56]
Hello,
I tried to add new tabs (based on a pub/sub collections empty or not), Tag is added but clicking on the tabs doesn't do anything. Is there something I missed ?
Thanks

**Comment by Zodiase** [comment]
Well, the current design of tabs (by MDL team, not by me) doesn't allow dynamic tabs, at least not very easily. Depending on what you want to achieve, #49 and #14 may or may not offer you some hints or potential workarounds. Maybe you could explain in a bit more detail what you have set up, the templates, relevant logic and stuff?

**Comment by Antoine-O** [comment]
It is quite straightforward code (iron router + blaze)

as long as OpenSize is not defined the tab is not displayed. 

OpenSize is based on the result of a collection


```
<div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
	<div class="mdl-tabs__tab-bar mdl-shadow--1dp"
		 style="background-color:#FFF; margin-bottom:10px">

		{{#if OpenSize}}
			<a href="#Open" class="mdl-tabs__tab">{{_ 'COMPETITION_OPEN_TITLE'}}
				({{OpenSize}})</a>
		{{/if}}
		{{#if NextSize}}
			<a href="#Next" class="mdl-tabs__tab">{{_ 'COMPETITION_NEXT_TITLE'}}
				({{NextSize}})</a>
		{{/if}}

		{{#if OverSize}}
			<a href="#Over"
			   class="mdl-tabs__tab">{{_ 'COMPETITION_OVER_TITLE'}}
				({{OverSize}})</a>
		{{/if}}

	</div>


	{{#if OpenSize}}
		<div class="mdl-tabs__panel" id="Open">
			<div class="mdl-grid" style="width: auto">
				{{#each Open}}
					<div class="mdl-cell mdl-cell--6-col" style="width: auto">
						{{> ListElement}}
					</div>
				{{/each}}
			</div>
		</div>
	{{/if}}

	{{#if NextSize}}
		<div class="mdl-tabs__panel" id="Next">
			<div class="mdl-grid" style="width: auto">
				{{#each Next}}
					<div class="mdl-cell mdl-cell--6-col" style="width: auto">
						{{> ListElement}}</div>
				{{/each}}</div>
		</div>
	{{/if}}          
	</div>          
</div>

```
helpers based on subscription


```
OpenSize: function () {
        var result;
        if (Template.instance().subscriptionsReady()) {
            var elements = QC_Element.find({status:"OPEN"});
            if (elements && elements.count() > 0) {
                result = elements.count();
            }
        }
        return result;
    },
```

**Comment by Zodiase** [comment]
@Antoine-O Could you try conditional showing/hiding elements instead of constructing/destructing them?

For example, instead of:
```HTML
	{{#if OpenSize}}
		<div class="mdl-tabs__panel" id="Open">
			<div class="mdl-grid" style="width: auto">
				{{#each Open}}
					<div class="mdl-cell mdl-cell--6-col" style="width: auto">
						{{> ListElement}}
					</div>
				{{/each}}
			</div>
		</div>
	{{/if}}
```

Change to:
```
	<div class="mdl-tabs__panel {{#unless OpenSize}}hidden{{/unless}}" id="Open">
		{{#if OpenSize}}
			<div class="mdl-grid" style="width: auto">
				{{#each Open}}
					<div class="mdl-cell mdl-cell--6-col" style="width: auto">
						{{> ListElement}}
					</div>
				{{/each}}
			</div>
		{{/if}}
	</div>
```

Not only will it be faster (Showing/hiding with CSS is always faster than removing/adding elements), it might just help resolve your issue. Just remember to try have all the tab subcomponents (including those tab buttons and tab panels) you need ready at once and not creating them dynamically. It's just simpler this way.

**Comment by Zodiase** [comment]
To recap what is covered in issue #14 and #49, the issue with MDL tabs is the fact that all the linkage (clicking some tab button opens what panel) is settled only once when the layout is being upgraded. So any new changes to the tab layout will likely break the linkage and release chaos :S

**Comment by Antoine-O** [comment]
yup that's what i read so far before creating a issue :/ 
I am inside a pretty big refactoring, i'll give try to the "show/hidden" way (I was thinking of that but I somwhat had some hope to a "regular" solution ;) )
thanks for support !

**Comment by Antoine-O** [comment]
this is worlking !
the use of hidden is magic ;) I used it only on mdl-tabs__tab element and it works like a charm ;)

                        <a href="#Open"
                           class="mdl-tabs__tab {{#unless sOpenSize}}hidden{{/unless}}">
                            ({{OpenSize}})</a>

**Comment by Zodiase** [comment]
@Antoine-O Glad it works for you. The trick is to have static button-panel pairs ready before the auto-upgrading.

By the way, just in case you didn't know, the use of class name `hidden` is just for illustration purpose and nobody should ever use a class name so generic. Please use good semantic class names :).

**Comment by Zodiase** [comment]
Seems the issue has been resolved. Closing.

**Comment by Antoine-O** [comment]
For the record, I had to implements dynmic tabs based on a dynamic list. Here is what I have done:

created tab and panel based on a static array
- tabs are hidden (as @Zodiase explains it earlier)
- panels are not (as they are shown only when)
then when new tab contents is found
- tab is "unhide" when necessary based on a {{#if}} or {{#unless}} clause.
- content are generated in a hidden place then moved with jquery in the right tab content

and if no tabs are selected :
- a click event is generated on the first tab, causing the first tab/content to be selected.
