### ISSUE TITLE
Multiple 'mdl-layout__container' class

### ISSUE THREAD

**Issue by kokjinsam** [Zodiase/meteor-mdl#6]
I have multiple layout templates that each contains different:

```
<div class="mdl-layout mdl-js-layout mdl-layout--[insert header style]">
  //layout
</div>
```

Whenever I load a new page with different layout, additional 

```
<div class="mdl-layout__container"></div> 
```

will be injected. For example, if I go to page 1 with layout 1, I will see one class="mdl-layout__container.  But if I go to page 2 with layout 2, I will see two class="mdl-layout__container. See below.

![image](https://cloud.githubusercontent.com/assets/9153498/8642580/d92f3454-28eb-11e5-97e7-27c26064beec.png)

**Comment by Zodiase** [comment]
I believe this could be solved quite similarly as issue #2. They are of the same cause.

Solution: Don't use mdl on the outer most element! Just add another wrapper around it would make you safe.

Cause: Blaze tracks the outer most element as the sort of "package box" of your templates. When another template (including layout) needs to replace the current one, the current "package box" gets removed from the DOM and the new one gets popped in. Now here's the ugly part: MDL layout components add an extra element outside for some reason (it's the `mdl-layout__container` you are seeing). If the outer most element of your template is the `mdl-layout` element, that container created by MDL would be outside of everything tracked by the current template, therefore it will be left when templates are swapping.
