### ISSUE TITLE
Upgrading issues/possible documentation extension?

### ISSUE THREAD

**Issue by arist0tl3** [Zodiase/meteor-mdl#60]
Hey @Zodiase -- thanks for this awesome package!

So I grokked the idea of wrapping components in order to have autoUpgrading work correctly. However, it took me a while to understand something like this:

```
<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" data-mdl-for="typeDrop">
  {{#if somethingExists}}
    <li class="mdl-menu__item js-set-type" data-type="members"></li>
  {{/if}}
</ul>
```

actually needs to be:

```
<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" data-mdl-for="typeDrop">
  {{#if somethingExists}}
    <div>
      <li class="mdl-menu__item js-set-type" data-type="members"></li>
    </div>
  {{/if}}
</ul>
```

Otherwise, the events don't fire correctly. In this example, if the `li` isn't wrapped, then the close menu event doesn't fire.

I've seen similar functionality when I have mdl elements inside of `{{#each}}` loops. Just wondering if it would be worth adding this sort of thing to the documentation, and also if this is the expected behavior?

**Comment by Zodiase** [comment]
Do you mean, in the first case, event handlers like `'click .js-set-type' (event, tplInst) {}` wouldn't work? That's interesting... I've not encountered it yet.

**Comment by Zodiase** [comment]
What is the `"close menu event"` you are talking about?

**Comment by arist0tl3** [comment]
So I was having issues with the mdl menus remaining open even after a selection had been made. I thought this was related to top-level mdl components within {{#if}} and {{#each}} tags, but I am not able to reproduce this now.

I'd say close this for now? Sorry!

**Comment by Zodiase** [comment]
The menu component detects clicks on items and then closes the menu. So technically if you intercepted the clicks and did something like `event.preventDefault(); event.stopPropagation();`, then most likely the menu wouldn't close. I had to use this deliberately to make a drop-down select list with search controls and other stuff in it. Some of the controls shouldn't close the menu.
