### ISSUE TITLE
Is there a method to hide the snackbar?

### ISSUE THREAD

**Issue by iandoesallthethings** [Zodiase/meteor-mdl#62]
Clicking the action button doesn't dismiss or hide it, meaning you can continually click the same action button. I can't seem to find any way to do it programmatically before its timeout.

**Comment by iandoesallthethings** [comment]
Nevermind! I found it:

 `snackbarContainer.classList.remove("mdl-snackbar--active"); 
`

**Comment by Zodiase** [comment]
@denkyuu I wouldn't recommend operating class lists directly. [The official guide](https://getmdl.io/components/index.html#snackbar-section) doesn't show examples of hiding the snackbar messages, however the API exists: https://github.com/google/material-design-lite/blob/mdl-1.x/src/snackbar/snackbar.js#L136

```JavaScript
snackbarContainer.MaterialSnackbar.hideSnackbar();
```

is probably what you want.

Also, preventing multiple triggering of some action is a pretty generic feature and could be achieved by disabling the trigger button or using [a function that may only be executed once](https://lodash.com/docs/4.17.4#once) as the action handler.

**Comment by iandoesallthethings** [comment]
I tried that, but it's throwing this:
`Uncaught TypeError: snackbarContainer.MaterialSnackbar.hideSnackbar is not a function at HTMLButtonElement.actionHandler (rehearsals.js:110)`

I'm 99% sure I'm fully updated, too. This is what I've got:

```
function snackbarMessage (label) {
  var snackbarContainer = document.querySelector('#catering-snackbar');

  if (!this.showingSnackbar) {
    var lastAction = Actions.find().fetch().slice(-1)[0];
    var data = {
      message: label,
      timeout: 5000,
      actionHandler: () => {
          cookList.undoAction(lastAction);
          //snackbarContainer.classList.remove("mdl-snackbar--active"); // Kill snackbar on press
          snackbarContainer.MaterialSnackbar.hideSnackbar(); // This exists, but is apparently hidden
      },
      actionText: "undo"
    };
    snackbarContainer.MaterialSnackbar.showSnackbar(data);
    this.showingSnackbar = true;
    window.setTimeout( () => {this.showingSnackbar = false;}, data.timeout);
  } else {
    // if there's already a snackbar, kill it and launch a new one
    //snackbarContainer.classList.remove("mdl-snackbar--active");
    snackbarContainer.MaterialSnackbar.hideSnackbar(); 
    this.showingSnackbar = false;
    snackbarMessage(label);
  }
}
```

**Comment by Zodiase** [comment]
@denkyuu Sorry about the confusion. Apparently the `hideSnackbar` hasn't made into the latest official release of MDL (1.3).

**Comment by Zodiase** [comment]
@denkyuu Until that API update is released, the closest you can get is:

```JavaScript
if (snackbarContainer.MaterialSnackbar.active) {
  snackbarContainer.MaterialSnackbar.cleanup_();
}
```

but doing so has its own bugs (probably why there wasn't a "hide" method in the first place). For example if you have consecutive snackbar messages, doing so would mess up the animation.

Here's a demo: https://github.com/Zodiase/Meteor-Tests/tree/mdl-snackbar

Clicking the `Show Snackbar` button multiple times to queue up several messages, and then click "Undo" in the first message, you'd see the animation of the second message got messed up.

**Comment by iandoesallthethings** [comment]
Ah, that answers my question. The cleanup function definitely is closest to what I was wanting, but you're right, it does bug out the animation pretty badly. It still looks like the hangup is related to the timeout. 

Thanks for the help!
