### ISSUE TITLE
zodiase:mdl > Settings file ignored: {zodiase:mdl}/zodiase-mdl.json

### ISSUE THREAD

**Issue by davidho8087** [Zodiase/meteor-mdl#63]
HI, 
I would like to ask why this message `zodiase:mdl > Settings file ignored: {zodiase:mdl}/zodiase-mdl.json` always promped in server each time the server refresh or rebuild?
For your information that i have the below setting in `zodiase-mdl.json` : 
```
{
  "theme": {
    "primary": "deep_orange",
    "accent": "blue"
  }
}
```
It this a problem ? if it is not , then how to hide/disable this log?
Here from you soon . Thanks!

**Comment by Zodiase** [comment]
No this does not indicate a problem.

I hope users could only put the config file under root directory to avoid confusion but the build plugin (in this package) actually sees all files matching the name so in a very early version I decided to show a message for every config file that's not in the root directory (so users know they have put the file in a wrong place).

Everything was fine until one day, MDG made a change to the build process so now ALL package files are considered part of the app, (so if I want to process all json files for example, I would see all json files not only in the app, but also in the package itself,) so this package would see the default config file under its own directory and show this note. I have an issue opened for this in the meteor/meteor repo. I don't think packages should be processing their own files. But so far MDG doesn't seem to understand what's wrong with it.

**Comment by Zodiase** [comment]
And... there's no way for you to hide it. If it really bothers you I could add an extra check (which I don't think is needed in the first place) to see if the config file is under any package.

**Comment by davidho8087** [comment]
Hi, 
Thank you for your explanation. I just leave this message since it can't change anything. 
let me know if there is any changes in future.
