### ISSUE TITLE
Fourseven upgrade not recommended ?

### ISSUE THREAD

**Issue by Antoine-O** [Zodiase/meteor-mdl#68]
Hello I am trying to upgrade fourseven:css to the last version, can I use --allow-incompatible-update ?

meteor add fourseven:scss@4.5.4
 => Errors while adding packages:

While selecting package versions:
error: Potentially incompatible change required to top-level dependency: zodiase:mdl 1.0.6_2, was 1.3.0.
Constraints on package "zodiase:mdl":

To allow potentially incompatible changes to top-level dependencies, you must pass --allow-incompatible-update on the command line.

**Comment by Antoine-O** [comment]
I am currently stuck with this as I can't install 1.3.0 because : 

        Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.0/win32-ia32-57_binding.node":

If you have some idea on how to fix it, I'll be sooooo glad.

**Comment by Zodiase** [comment]
@Antoine-O I have a somewhat ad-hoc solution for you (until I release a new patch).

- First make sure your project is under proper version control so we don't mess up anything...
- Then stop the Meteor instance if it's running.
- If you encounter any strange errors below, complaining about version incompatibility, you probably need to uninstall both `zodiase:mdl` and `fourseven:scss` first, in that order. And then add `fourseven:scss` back. Make sure it's at the version you want.
- Download the entire package source of `zodiase:mdl-assets` from https://github.com/Zodiase/meteor-mdl-assets and place it under `/packages` in your project. Let's name it as `zodiase_mdl-assets` for example.
- Download the `meteor-package` folder from https://github.com/Zodiase/meteor-mdl and place it under `/packages` in your project as well. Let's name it as `zodiase_mdl` for example.
- Now you need to modify `/packages/zodiase_mdl/package.js` and `/packages/zodiase_mdl-assets/package.js`. Open both files and you should see some dependency declarations neatly at line 6 in both of them. Change `'SCSS': 'fourseven:scss@3.8.1',` to whatever version you need. Perhaps you'd need to change `'Meteor': '1.3.5',` as well. I think simply changing all those to your matching versions should do the work.
- **Navigate to `/packages/zodiase_mdl-assets` and run `meteor test-packages ./`, then terminate the process once it's running. This should make sure all NPM dependencies are installed.**
- **Navigate to `/packages/zodiase_mdl` and run `npm i` to install dependencies.**
- Now you may need to run `meteor add zodiase:mdl` in your app directory.
- Well... Let me know if any error pops up XD

I'll now test these steps locally and let you know if I missed anything.

**Comment by Zodiase** [comment]
Added the two steps (in bold) I missed. Now I realize there might be another issue. `zodiase:mdl-assets` uses two symlinks. Not sure if they would work fine for you on Windows. Crossing my fingers.

**Comment by Zodiase** [comment]
@Antoine-O Hey, good news! With the latest release `zodiase:mdl@1.3.0_1`, you should be able to use `fourseven:scss@4.5.4`! And never mind the workaround steps above.

**Comment by Antoine-O** [comment]
Thanks @Zodiase ! It seems to work so far :) 
Anyway the steps above maybe useful in a near future ;)
