### ISSUE TITLE
Menus not working

### ISSUE THREAD

**Issue by Cirych** [Zodiase/meteor-mdl#8]
Menu items not respond on click event in helper. Only menu button can do it.

**Comment by Zodiase** [comment]
Could you be more specific or better provide a demo reproducing the error?

**Comment by Cirych** [comment]
index.html
--------------
  <button id="demo-menu-lower-left"
        class="mdl-button mdl-js-button mdl-button--icon">
  <i class="material-icons">more_vert</i>
</button>

<ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
    for="demo-menu-lower-left">
  <li class="mdl-menu__item">Some Action</li>
  <li class="mdl-menu__item">Another Action</li>
  <li disabled class="mdl-menu__item">Disabled Action</li>
  <li class="mdl-menu__item">Yet Another Action</li>
</ul>

app.js
----------
Template.body.events({
    'click': function (event) {
      console.log(event);
    }
  });
-------------------------------------

Click event works only on button, not on menu items.

**Comment by Cirych** [comment]
index.html

``` html
  <button id="demo-menu-lower-left"
        class="mdl-button mdl-js-button mdl-button--icon">
  <i class="material-icons">more_vert</i>
</button>

<ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
    for="demo-menu-lower-left">
  <li class="mdl-menu__item">Some Action</li>
  <li class="mdl-menu__item">Another Action</li>
  <li disabled class="mdl-menu__item">Disabled Action</li>
  <li class="mdl-menu__item">Yet Another Action</li>
</ul>
```

app.js

``` js
Template.body.events({
    'click': function (event) {
      console.log(event);
    }
  });
```

Click event works only on button, not on menu items.

**Comment by Zodiase** [comment]
Duplicate to issue #2.
Try avoid using mdl elements on the root level of any template.
In other words, always have a non-mdl wrapper around templates.

See the demo code for this issue for details.
Closed.
