### ISSUE TITLE
Icons on Cordova

### ISSUE THREAD

**Issue by benjick** [Zodiase/meteor-mdl#9]
Hey

When building for cordova (android and android-device) icons are just displayed as text.

Can be tried with https://github.com/benjick/droidarr -> meteor run android

**Comment by benjick** [comment]
![screenshot_2015-07-21-16-51-38 1](https://cloud.githubusercontent.com/assets/430872/8803757/f634cea4-2fc8-11e5-8505-5eed9733a2db.png)

Example, menu and search icons

**Comment by Zodiase** [comment]
Well, the icon font is not included in the package, but instead downloaded from google fonts api so you would need network access and whitelist https://fonts.googleapis.com/

**Comment by Zodiase** [comment]
Possibly also need to whitelist https://fonts.gstatic.com/ since that's where the type faces are.

**Comment by benjick** [comment]
I see, I only whitelisted http://*. Thank you
